title: Radio Player
description: A simple set of configuration files to make a station at the top of your page.
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
